variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

stages:
    - build
    - security

maven:
    image: maven:3.6.0-jdk-8
    stage: build
    cache:
        paths:
            - .m2/repository
        key: "$CI_JOB_NAME"
    script:
        - mvn $MAVEN_CLI_OPTS clean package
    artifacts:
        paths:
            - target/

veracode_greenlight:
    image: openjdk:8-jre
    stage: security
    before_script:
        - curl -sS -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
        - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
    script:
        - java -jar gl-scanner-java.jar -i $VERACODE_ID -k $VERACODE_KEY
          --source_dir src/main/java/ --build_dir target/classes/
          --project_name "$CI_PROJECT_NAME" --project_ref $CI_COMMIT_REF_NAME --project_url $CI_PROJECT_URL
          --issue_details=true --summary_output=true
    artifacts:
        name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA-greenlight_results"
        paths:
            - results.json
            - results.txt