name: Veracode Dynamic Analysis
on: workflow_dispatch
    
jobs:
  static_analysis:
    name: Veracode Dynamic Analysis
    env:
      API_ID: ${{ secrets.VERACODE_API_ID }}
      API_KEY: ${{ secrets.VERACODE_API_KEY }}
    runs-on: ubuntu-latest

    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          python -V
          pip install -r vera-scripts/requirements.txt
          python vera-scripts/create-da-scan.py
