name: Veracode Copied

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read
# This first step is assumed to exist already in your Workflow
jobs:
  build-scan:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.3
        with:
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          file: target/verademo.war 
          fail_build: false

# This step will import the flaws from the step above
  import-issues:
    permissions:
      issues: write
    needs: build-scan
    runs-on: ubuntu-latest
    steps:
      - name: get scan results
        uses: actions/download-artifact@v3
        with:
          name: Veracode Pipeline-Scan Results

      - name: import flaws as issues
        uses: veracode/veracode-flaws-to-issues@v2.1.10
        with:
          scan-results-json: 'results.json'

# This step will use the Veracode SCA action
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Veracode SCA
        uses: veracode/veracode-sca@WorkspaceAutomation
        with:
          workspace_automation: true
          VID: '${{ secrets.VERACODE_API_ID }}'
          VKEY: '${{ secrets.VERACODE_API_KEY }}'